### ISSUE TITLE
no such table: gallery_photo

### ISSUE THREAD

**Issue by sunqy1212** [aaugustin/myks-gallery#1]
I want to try the example but it told me:"no such table: gallery_photo",how to fix it

**Comment by aaugustin** [comment]
Did you run manage.py migrate?

**Comment by sunqy1212** [comment]
yes,I did. Is it caused by the Django version?My Django is 1.9.5，I will try Djang1.10 later ,but I do not think it maters much.

**Comment by aaugustin** [comment]
Ah, it looks like I never generated migrations for this project, so it doesn't work in projects started with Django 1.9 or later. I'll take care of that.

**Comment by aaugustin** [comment]
Fixed in version 0.6.
