### ISSUE TITLE
Issue with the example

### ISSUE THREAD

**Issue by irfahlevi** [aaugustin/myks-gallery#3]
Hi, I tried to use the example folder. Everything is ok till I try to scan the folder. It is said ?photo.jpg or ? 2013_01_01_Featured Pictures\photo1.jpg

need help..

**Comment by aaugustin** [comment]
I believe this happens when none of your `GALLERY_PATTERNS` match.

**Comment by irfahlevi** [comment]
Hi, 

Currently, it is like this 
GALLERY_PATTERNS = (
    ('Photos', r'(?P<a_year>\d{4})_(?P<a_month>\d{2})_(?P<a_day>\d{2})_'
               r'(?P<a_name>[^/]+)/[^/]+.(jpg|JPG)'),
)

I think everything is the same. I check my folder name and structure.. 
The problem is still happen. I am on django 1.11.7 now

**Comment by aaugustin** [comment]
I'm sorry you didn't have a better experience with myks-gallery. I don't have time to debug this over GitHub issues. I hope you figured it out.
