### ISSUE TITLE
How to configure properly these 2 settings GALLERY_PHOTO_DIR and GALLERY_PHOTO_STORAGE

### ISSUE THREAD

**Issue by iocohen** [aaugustin/myks-gallery#4]
GALLERY_PHOTO_DIR = os.path.join(BASE_DIR, 'media')
GALLERY_PHOTO_STORAGE = os.path.join(BASE_DIR, 'media')

I got this error: ```
ImportError at /admin/gallery/photo/scan/
/Users/Desktop/chn2/chn/media doesn't look like a module path
```

**Comment by aaugustin** [comment]
It's a "dotted Python path to a storage backend".

Perhaps the example can help you:
- https://github.com/aaugustin/myks-gallery/blob/ea5294475a045fbea65df895bf2111abe27a0cf5/example/example/settings.py#L75
https://github.com/aaugustin/myks-gallery/blob/ea5294475a045fbea65df895bf2111abe27a0cf5/example/example/storages.py#L12-L13
